version: '3.3'
services:
  backend:
    image: motherbrain-full-stack-challenge/backend:latest
    build: backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 8080:8080
    environment:
      ES_URL: ${ES_URL}
    command: ["yarn", "docker"]

  frontend:
    image: motherbrain-full-stack-challenge/frontend:latest
    build: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    command: ["yarn", "dev"]
